field: 2f62822f-1988-45e3-8f83-21ae822c27d0 # Content Builder
fieldLayouts:
  6b1aabc1-f28c-45c1-9be8-33d100980ee4:
    tabs:
      -
        elements:
          -
            fieldUid: 01e6d8f1-d486-46cd-8f6a-041b0c385e29 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 993fc0e0-9139-4c80-977b-25a5d4830b7e # Target
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  01e6d8f1-d486-46cd-8f6a-041b0c385e29: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  993fc0e0-9139-4c80-977b-25a5d4830b7e: # Target
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: buttonTarget
    instructions: ''
    name: Target
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: button
name: Button
sortOrder: 2
