baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-GB
name: 'NextJS Headless (CMS)'
primary: true
siteGroup: 0050a0e9-bdcc-4fb3-918e-bc4c1bc3e1cb # NextJS Headless (CMS)
sortOrder: 1
