columnSuffix: null
contentColumnType: string
fieldGroup: 1441a512-dcc6-499d-b283-423d6bd2d78e # Content
handle: contentBuilder
instructions: ''
name: 'Content Builder'
searchable: false
settings:
  contentTable: '{{%matrixcontent_contentbuilder}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
